"""adding product table

Revision ID: 70055e3854da
Revises: 883365d69517
Create Date: 2024-04-12 06:39:37.333095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70055e3854da'
down_revision: Union[str, None] = '883365d69517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 0', name='attribute_name_length_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_attribute_name')
    )
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 0', name='product_type_name_length_check'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'level', name='uq_product_type_name_level')
    )
    op.drop_constraint('unq_category_name_level', 'category', type_='unique')
    op.create_unique_constraint('uq_category_name_level', 'category', ['name', 'level'])
    op.drop_constraint('unq_product_name_level', 'product', type_='unique')
    op.drop_constraint('unq_product_name_slug', 'product', type_='unique')
    op.create_unique_constraint('uq_product_name_level', 'product', ['name'])
    op.create_unique_constraint('uq_product_name_slug', 'product', ['slug'])
    op.create_unique_constraint('uq_product_pid', 'product', ['pid'])
    op.drop_constraint('unq_product_image_line_order_product_id', 'product_image', type_='unique')
    op.create_unique_constraint('uq_product_image_line_order_product_id', 'product_image', ['order', 'product_line_id'])
    op.drop_constraint('unq_product_line_order_product_id', 'product_line', type_='unique')
    op.create_unique_constraint('uq_product_line_order_product_id', 'product_line', ['order', 'product_id'])
    op.create_unique_constraint('uq_product_line_sku', 'product_line', ['sku'])
    op.drop_constraint('unq_seasonal_event_name', 'seasonal_event', type_='unique')
    op.create_unique_constraint('uq_seasonal_event_name', 'seasonal_event', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_seasonal_event_name', 'seasonal_event', type_='unique')
    op.create_unique_constraint('unq_seasonal_event_name', 'seasonal_event', ['name'])
    op.drop_constraint('uq_product_line_sku', 'product_line', type_='unique')
    op.drop_constraint('uq_product_line_order_product_id', 'product_line', type_='unique')
    op.create_unique_constraint('unq_product_line_order_product_id', 'product_line', ['order', 'product_id'])
    op.drop_constraint('uq_product_image_line_order_product_id', 'product_image', type_='unique')
    op.create_unique_constraint('unq_product_image_line_order_product_id', 'product_image', ['order', 'product_line_id'])
    op.drop_constraint('uq_product_pid', 'product', type_='unique')
    op.drop_constraint('uq_product_name_slug', 'product', type_='unique')
    op.drop_constraint('uq_product_name_level', 'product', type_='unique')
    op.create_unique_constraint('unq_product_name_slug', 'product', ['slug'])
    op.create_unique_constraint('unq_product_name_level', 'product', ['name'])
    op.drop_constraint('uq_category_name_level', 'category', type_='unique')
    op.create_unique_constraint('unq_category_name_level', 'category', ['name', 'level'])
    op.drop_table('product_type')
    op.drop_table('attribute')
    # ### end Alembic commands ###
