"""added seasonal event tb

Revision ID: 883365d69517
Revises: fbf26aace9f5
Create Date: 2024-04-11 07:55:15.308581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883365d69517'
down_revision: Union[str, None] = 'fbf26aace9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasonal_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.CheckConstraint('LENGTH(name) > 0', name='season_event_name_length_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unq_seasonal_event_name')
    )
    op.drop_constraint('unq_category_name_level', 'category', type_='unique')
    op.create_unique_constraint('unq_category_name_level', 'category', ['name', 'level'])
    op.add_column('product', sa.Column('seasonal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'seasonal_event', ['seasonal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'seasonal_id')
    op.drop_constraint('unq_category_name_level', 'category', type_='unique')
    op.create_unique_constraint('unq_category_name_level', 'category', ['slug'])
    op.drop_table('seasonal_event')
    # ### end Alembic commands ###
