"""db complete

Revision ID: 8cd7ec5fa378
Revises: 43697f44d88d
Create Date: 2024-04-12 07:13:05.224665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd7ec5fa378'
down_revision: Union[str, None] = '43697f44d88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_type_id', 'product_id', name='uq_product_id_product_type_id')
    )
    op.drop_constraint('uq_category_name_level', 'category', type_='unique')
    op.create_unique_constraint('uq_category_name_level', 'category', ['name', 'level'])
    op.alter_column('product_line_attribute_value', 'attribute_value_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_line_attribute_value', 'attribute_value_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_category_name_level', 'category', type_='unique')
    op.create_unique_constraint('uq_category_name_level', 'category', ['slug'])
    op.drop_table('product_product_type')
    # ### end Alembic commands ###
